// <auto-generated />
namespace Infrastrucure.Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class init_TaskType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init_TaskType));
        
        string IMigrationMetadata.Id
        {
            get { return "202310121021389_init_TaskType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
