// <auto-generated />
namespace Infrastrucure.Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Samaneh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Samaneh));
        
        string IMigrationMetadata.Id
        {
            get { return "202307261506365_Samaneh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
