// <auto-generated />
namespace Infrastrucure.Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_RoadmapLesson : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_RoadmapLesson));
        
        string IMigrationMetadata.Id
        {
            get { return "202310281933094_Add_RoadmapLesson"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
