// <auto-generated />
namespace Infrastrucure.Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _init_unique : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_init_unique));
        
        string IMigrationMetadata.Id
        {
            get { return "202310152005559__init_unique"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
