// <auto-generated />
namespace Infrastrucure.Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _history : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_history));
        
        string IMigrationMetadata.Id
        {
            get { return "202311190807582__history"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
